[KZ4112] Adiciona timeout na request da gem da TWW
clicksign/tww pull request #7
Opened 2020-11-26 12:01 UTC by romarioddo

[KZ4112](https://clicksign.kanbanize.com/ctrl_board/28/cards/4112/details/)

2020-11-26 20:17 UTC, fabiodallazen requested changes

2020-11-26 20:17 UTC, fabiodallazen commented on .gitignore
> +.idea
Coloca este cara somente no teu gitignore local @romarioddo

2020-11-27 01:25 UTC, mbbernstein commented on lib/tww/config.rb
> +  Config = Struct.new(:username, :password, :from, :layout, :timeout) do
Timeout poderia ter um valor default.

2020-11-27 14:53 UTC, romarioddo commented on .gitignore
> +.idea
:+1:

2020-11-27 14:55 UTC, romarioddo commented on lib/tww/config.rb
> +  Config = Struct.new(:username, :password, :from, :layout, :timeout) do
@mbbernstein a gem do restclient já assume um valor padrão de [timeout](https://github.com/rest-client/rest-client#timeouts).

Vamos enviar esse parâmetro do tavola com um valor default e vamos permitir mudar ele através da tabela `Config`

2020-11-30 17:17 UTC, dlibanori approved these changes

2020-11-30 18:28 UTC, fabiodallazen approved these changes

2020-12-01 12:08 UTC, merged